---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: Europe/London
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Smart Data Hack"
keywords:    "smart data hack, ilwhack, informatics, university of edinburgh, ilw, innovatio lab"
description: "Home page for the University of Edinburgh Smart Data Hack"
source_link: "https://github.com/ilwhack/ilwhack.github.io"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  darkred:   '#940a3d'
  limegreen: '#82940a'
  softgreen: '#0a9461'
  darkblue:  '#240563'
